---
- name: deploy application
  hosts: openshift
  vars:
    - openshift_namespace: "http"
    - quay_repo: "andromeda07.sales.lab.tlv.redhat.com:30080/quay/nginx-hello"
  tasks:
    - name: Create a k8s namespace
      k8s_raw:
        name: "{{ openshift_namespace }}"
        api_version: v1
        kind: Namespace
        state: present

    - name: build application
      shell: oc process --template=httpd-example --param=SOURCE_REPOSITORY_URL=https://github.com/openshift/httpd-ex.git | oc create -f - -n http
    
   # - name: creating nginx application
   #   shell: oc new-app --docker-image="{{ quay_repo }}" -n "{{ openshift_namespace }}"