---
- name: openshift pre
  hosts: openshift
  vars:
<<<<<<< HEAD
    - redhat_user: asafh@redhat.com
    - redhat_user_password: Copper123
    - redhat_pool_id: 8a85f98c60c2c2b40160c31904b30447
    - docker_version: docker-1.13.1
=======
    - redhat_user: 
    - redhat_user_password: 
    - redhat_pool_id: 
    - docker_version: docker-1.12.6
>>>>>>> b5e30d7e40cc09b46dad5a1b9c795287e17ab8bf
  gather_facts: no
  tasks:
    - name: Host Registration
      redhat_subscription:
        state: present
        username: "{{ redhat_user }}"
        password: "{{ redhat_user_password }}"
        pool_ids: "{{ redhat_pool_id }}"

    - name: Disable all repositories [dirty, using shell module]
      shell: subscription-manager repos --disable="*"

    - name: Enable required repositories [dirty, using shell module]- 
      shell: subscription-manager repos --enable="{{item}}"
      with_items: 
        - rhel-7-server-rpms
        - rhel-7-server-extras-rpms
        - rhel-7-server-ose-3.10-rpms
        - rhel-7-fast-datapath-rpms
        - rhel-7-server-ansible-2.4-rpms

    - name: Installing base packages using yum
      yum:
        name: "{{ item }}"
        state: latest
      with_items: 
        - wget 
        - git 
        - net-tools 
        - bind-utils 
        - yum-utils 
        - iptables-services 
        - bridge-utils 
        - bash-completion 
        - kexec-tools 
        - sos 
        - psacct
        - ceph-common

    - name: update system
      yum:
        name: '*'
        state: latest

    - name: Installing specific version of docker
      yum:
        name: "{{ docker_version }}"
        state: present
      notify: restart docker

    - name: Copy docker-storage-setup to the host
      copy:
        src: ./docker-storage-setup
        dest: /etc/sysconfig/docker-storage-setup
      notify: docker-storage-setup

    - name: Copy docker daemon config
      copy:
        src: ./daemon.json
        dest: /etc/docker/daemon.json
      notify: restart docker 

    - name: enable docker
      service:
        name: docker
        enabled: true

  handlers:
    - name: docker-storage-setup
      shell: docker-storage-setup

    - name: restart docker
      service:
        name: docker
        state: restarted
    


...
