---
- name: post installation
  hosts: all
  tasks:
    - name: setting admin user
      shell: htpasswd -b /etc/origin/master/htpasswd admin admin

    - name: give privileges to admin
      shell: oadm policy add-cluster-role-to-user cluster-admins admin; oadm policy add-cluster-role-to-user admin admin