apiVersion: v1
kind: Service
metadata:
  namespace: postgres
  name: postgres
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 30543
  selector:
    app: postgres
