---
# tasks file for openshift-node
- name: Host Registration
  redhat_subscription:
    state: present
    username: "{{ redhat_user }}"
    password: "{{ redhat_user_password }}"
    pool_ids: "{{ redhat_pool_id }}"

- name: Disable all repositories [dirty, using shell module]
  shell: subscription-manager repos --disable="*"

- name: Disable enable required repositories [dirty, using shell module]- 
  shell: subscription-manager repos --enable="{{item}}"
  with_items: "{{ enable_repo_list }}"

- name: Installing base packages using yum
  yum:
    name: "{{ item }}"
    state: latest
  with_items: "{{ base_packages }}"

- name: update system
  yum:
    name: '*'
    state: latest

- name: Installing specific version of docker
  yum:
    name: "{{ docker_version }}"
    state: present
  notify: restart docker

- name: Copy docker-storage-setup to the host
  copy:
    src: "{{ role_path }}/template/docker-storage-setup"
    dest: /etc/sysconfig/docker-storage-setup
  notify: restart docker

